"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICryptoPunksMarket__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "punkIndex",
                type: "uint256",
            },
        ],
        name: "buyPunk",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "punkIndex",
                type: "uint256",
            },
        ],
        name: "transferPunk",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ICryptoPunksMarket__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICryptoPunksMarket__factory = ICryptoPunksMarket__factory;
ICryptoPunksMarket__factory.abi = _abi;
