"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Permit2Payments__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "FromAddressIsNotOwner",
        type: "error",
    },
    {
        inputs: [],
        name: "InsufficientETH",
        type: "error",
    },
    {
        inputs: [],
        name: "InsufficientToken",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidBips",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidSpender",
        type: "error",
    },
];
class Permit2Payments__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.Permit2Payments__factory = Permit2Payments__factory;
Permit2Payments__factory.abi = _abi;
