import { ChainId, Currency, NativeCurrency, Token } from '@uniswap/sdk-core';
export declare const NATIVE_CHAIN_ID = "NATIVE";
export declare const USDC_MAINNET: any;
export declare const USDC_GOERLI: any;
export declare const USDC_SEPOLIA: any;
export declare const USDC_OPTIMISM: any;
export declare const USDC_OPTIMISM_GOERLI: any;
export declare const USDC_ARBITRUM: any;
export declare const USDC_ARBITRUM_GOERLI: any;
export declare const USDC_POLYGON: any;
export declare const USDC_POLYGON_MUMBAI: any;
export declare const USDC_CELO: any;
export declare const USDC_BASE: any;
export declare const DAI: any;
export declare const DAI_ARBITRUM_ONE: any;
export declare const DAI_OPTIMISM: any;
export declare const MATIC_MAINNET: any;
export declare const MATIC_POLYGON: any;
export declare const DAI_POLYGON: any;
export declare const USDT_POLYGON: any;
export declare const WBTC_POLYGON: any;
export declare const USDT: any;
export declare const USDT_ARBITRUM_ONE: any;
export declare const USDT_OPTIMISM: any;
export declare const WBTC: any;
export declare const WBTC_ARBITRUM_ONE: any;
export declare const WBTC_OPTIMISM: any;
export declare const WETH_POLYGON_MUMBAI: any;
export declare const WETH_POLYGON: any;
export declare const CUSD_CELO: any;
export declare const CEUR_CELO: any;
export declare const PORTAL_ETH_CELO: any;
export declare const WBTC_CELO: any;
export declare const CUSD_CELO_ALFAJORES: any;
export declare const CEUR_CELO_ALFAJORES: any;
export declare const USDC_BSC: any;
export declare const USDT_BSC: any;
export declare const ETH_BSC: any;
export declare const BTC_BSC: any;
export declare const BUSD_BSC: any;
export declare const DAI_BSC: any;
export declare const USDB_BLAST: any;
export declare const USDC_AVALANCHE: any;
export declare const USDT_AVALANCHE: any;
export declare const WETH_AVALANCHE: any;
export declare const DAI_AVALANCHE: any;
export declare const UNI: {
    [chainId: number]: Token;
};
export declare const ARB: any;
export declare const OP: any;
export declare const LDO: any;
export declare const NMR: any;
export declare const MNW: any;
export declare const WRAPPED_NATIVE_CURRENCY: {
    [chainId: number]: Token | undefined;
};
export declare function isCelo(chainId: number): chainId is ChainId.CELO | ChainId.CELO_ALFAJORES;
export declare function isPolygon(chainId: number): chainId is ChainId.POLYGON | ChainId.POLYGON_MUMBAI;
export declare function isBsc(chainId: number): chainId is ChainId.BNB;
export declare function isAvalanche(chainId: number): chainId is ChainId.AVALANCHE;
export declare function nativeOnChain(chainId: number): NativeCurrency | Token;
export declare const TOKEN_SHORTHANDS: {
    [shorthand: string]: {
        [chainId in ChainId]?: string;
    };
};
export declare function isStablecoin(currency?: Currency): boolean;
export declare const UNKNOWN_TOKEN_SYMBOL = "UNKNOWN";
export declare const UNKNOWN_TOKEN_NAME = "Unknown Token";
