declare const TAG = " | midgard network | ";
declare let SEED_TESTNET: string;
declare const MIDGARD_API = "https://midgard.thorchain.info/v2";
declare let URL_THORNODE: string;
declare const Axios: any;
declare const https: any;
declare const axios: any;
declare const log: any;
declare const get_new_addresses: () => Promise<any>;
declare const get_price: (asset: string) => Promise<any>;
declare const get_pool_addresses: () => Promise<any>;
declare const get_info: () => Promise<any>;
declare const get_pools: () => Promise<any>;
declare const get_pool: (poolId: string) => Promise<any>;
